on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  pr-warning:
    runs-on: ubuntu-latest
    name: A job to warn the submitting user
    steps:
      - name: Post the warning
        uses: megan07/pr-warning@master
        id: pr-warning
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          warning: "Ahhhh!"
